import { PlayerDataTypes } from "../components/Types/Types";

export const leagueOptions = [
  { value: "Laliga", label: "Laliga" },
  { value: "League1", label: "League 1" },
  { value: "League2", label: "League 2" },
];

export const statusOptions = [
  { value: "Forward", label: "Forward" },
  { value: "Backward", label: "Backward" },
  { value: "Midfielder", label: "Midfielder" },
];
export const PlayingStatus = [
  { value: "Active", label: "Active" },
  { value: "Retired", label: "Retired" },
];
export const playersList: PlayerDataTypes[] = [
  {
    id: 1,
    user: "Lionel Messi",
    age: 37,
    leagues: ["Laliga", "League 1", "League 2", "League 3", "League 4"],
    status: "Active",
    height: "1.70 m",
    position: "Forward",
  },
  {
    id: 2,
    user: "Cristiano Ronaldo",
    age: 39,
    leagues: ["Laliga", "League 1"],
    status: "Active",
    height: "1.87 m",
    position: "Forward",
  },
  {
    id: 3,
    user: "Thierry Henry",
    age: 47,
    leagues: ["Laliga", "League 1"],
    status: "Retired",
    height: "1.87 m",
    position: "Forward",
  },
  {
    id: 4,
    user: "Zinedine Zidane",
    age: 52,
    leagues: ["Laliga", "League 1", "League 2"],
    status: "Retired",
    height: "1.87 m",
    position: "Mid-fielder",
  },
  {
    id: 5,
    user: "Luka Modrić",
    age: 39,
    leagues: ["Laliga", "League 1", "League 2"],
    status: "Active",
    height: "1.87 m",
    position: "Forward",
  },
  {
    id: 6,
    user: "Neymar Jr.",
    age: 32,
    leagues: ["Laliga", "League 1"],
    status: "Active",
    height: "1.75 m",
    position: "Forward",
  },
  {
    id: 7,
    user: "Kylian Mbappé",
    age: 25,
    leagues: ["Ligue 1", "World Cup"],
    status: "Active",
    height: "1.78 m",
    position: "Forward",
  },
  {
    id: 8,
    user: "Robert Lewandowski",
    age: 35,
    leagues: ["Bundesliga", "La Liga"],
    status: "Active",
    height: "1.85 m",
    position: "Forward",
  },
  {
    id: 9,
    user: "Sergio Ramos",
    age: 37,
    leagues: ["La Liga", "League 1"],
    status: "Active",
    height: "1.84 m",
    position: "Defender",
  },
  {
    id: 10,
    user: "Paul Pogba",
    age: 30,
    leagues: ["Premier League", "Serie A"],
    status: "Active",
    height: "1.91 m",
    position: "Midfielder",
  },
  {
    id: 11,
    user: "Eden Hazard",
    age: 33,
    leagues: ["Premier League", "La Liga"],
    status: "Retired",
    height: "1.75 m",
    position: "Forward",
  },
  {
    id: 12,
    user: "Sadio Mané",
    age: 32,
    leagues: ["Premier League", "Bundesliga"],
    status: "Active",
    height: "1.75 m",
    position: "Forward",
  },
  {
    id: 13,
    user: "Kevin De Bruyne",
    age: 33,
    leagues: ["Premier League"],
    status: "Active",
    height: "1.81 m",
    position: "Midfielder",
  },
  {
    id: 14,
    user: "Gareth Bale",
    age: 35,
    leagues: ["Premier League", "La Liga"],
    status: "Retired",
    height: "1.85 m",
    position: "Forward",
  },
  {
    id: 15,
    user: "Gerard Piqué",
    age: 37,
    leagues: ["La Liga"],
    status: "Retired",
    height: "1.94 m",
    position: "Defender",
  },
  {
    id: 16,
    user: "Karim Benzema",
    age: 36,
    leagues: ["La Liga"],
    status: "Active",
    height: "1.85 m",
    position: "Forward",
  },
  {
    id: 17,
    user: "Virgil van Dijk",
    age: 33,
    leagues: ["Premier League"],
    status: "Active",
    height: "1.93 m",
    position: "Defender",
  },
  {
    id: 18,
    user: "Alisson Becker",
    age: 31,
    leagues: ["Premier League"],
    status: "Active",
    height: "1.93 m",
    position: "Goalkeeper",
  },
  {
    id: 19,
    user: "Leroy Sané",
    age: 28,
    leagues: ["Bundesliga", "Premier League"],
    status: "Active",
    height: "1.83 m",
    position: "Forward",
  },
  {
    id: 20,
    user: "Marcus Rashford",
    age: 26,
    leagues: ["Premier League"],
    status: "Active",
    height: "1.85 m",
    position: "Forward",
  },
];
